In [15]:
x = np.array([[1.0,1.0],[1.5,2.0],[3.0,4.0],[5.0,7.0],[3.5,5.0],[4.5,5.0]])
y = np.array(['A','A','B','B','B','B'])

In [17]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x, y)

KNeighborsClassifier(n_neighbors=3)

In [21]:
new_point = np.array([[2.0,3.0]])
predicted_class = knn.predict(new_point)

In [25]:
print('The predicted class is:', predicted_class[0])

The predicted class is: A


In [33]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pandas as pd

In [37]:
df= pd.read_csv('Heart_Attack_Data_Set.csv')
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [39]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [45]:
from sklearn.preprocessing import LabelEncoder as LE

In [47]:
le_age= LE()

In [49]:
df['age']= le_age.fit_transform(df['age'])
df['age']

0      29
1       3
2       7
3      22
4      23
       ..
298    23
299    11
300    34
301    23
302    23
Name: age, Length: 303, dtype: int64

In [53]:
le_trestbps =LE()
df['trestbps'] = le_trestbs.fit_transform(df['trestbps'])
df['trestbps']

0      31
1      22
2      22
3      14
4      14
       ..
298    28
299     8
300    30
301    22
302    22
Name: trestbps, Length: 303, dtype: int64

In [55]:
le_chol =LE()
df['chol'] = le_trestbs.fit_transform(df['chol'])
df['chol']

0       64
1       80
2       35
3       67
4      145
      ... 
298     71
299     93
300     26
301      1
302     67
Name: chol, Length: 303, dtype: int64

In [57]:
le_thalach =LE()
df['thalach'] = le_trestbs.fit_transform(df['thalach'])
df['thalach']

0      49
1      84
2      71
3      76
4      62
       ..
298    23
299    32
300    40
301    16
302    73
Name: thalach, Length: 303, dtype: int64

In [61]:
le_oldpeak = LE()
df['oldpeak'] = le_oldpeak.fit_transform(df['oldpeak'])
df['oldpeak']

0      22
1      32
2      14
3       8
4       6
       ..
298     2
299    12
300    31
301    12
302     0
Name: oldpeak, Length: 303, dtype: int64

In [153]:
import pandas as pd

In [155]:
df = pd.read_csv('diabetes.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
762            9       89             62              0        0  22.5   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
762                     0.142   33        0  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  

[767 rows x 9 columns]

In [157]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [159]:
x = df.drop(columns = ['Outcome'])
y = df['Outcome']

In [161]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
762            9       89             62              0        0  22.5   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
762                     0.142   33  
763                     0.171   63  
764                     0.340   27  
765                     0.245   30  
766                     0.349   47  

[767 rows x 8 columns]

In [163]:
y

0      1
1      0
2      1
3      0
4      1
      ..
762    0
763    0
764    0
765    0
766    1
Name: Outcome, Length: 767, dtype: int64

In [165]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test, = train_test_split(x,y, test_size=0.2, random_state= 42)  

In [167]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [169]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [171]:
knn.fit(x_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [173]:
y_pred = knn.predict(x_test_scaled)
y_pred

array([1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
      dtype=int64)

In [175]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print (f'Accuary:{accuracy:.2f}')
print ("\nClassification Report:")
print (classification_report(y_test, y_pred))
print ("\nConfuion Matrix:")
print (confusion_matrix(y_test, y_pred))

Accuary:0.69

Classification Report:
              precision    recall  f1-score   support

           0       0.77      0.77      0.77       103
           1       0.54      0.55      0.54        51

    accuracy                           0.69       154
   macro avg       0.66      0.66      0.66       154
weighted avg       0.70      0.69      0.70       154


Confuion Matrix:
[[79 24]
 [23 28]]


In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('mushroom_cleaned.csv')
df

cap-diameter  cap-shape  gill-attachment  gill-color  stem-height  \
0              1372          2                2          10     3.807467   
1              1461          2                2          10     3.807467   
2              1371          2                2          10     3.612496   
3              1261          6                2          10     3.787572   
4              1305          6                2          10     3.711971   
...             ...        ...              ...         ...          ...   
54030            73          5                3           2     0.887740   
54031            82          2                3           2     1.186164   
54032            82          5                3           2     0.915593   
54033            79          2                3           2     1.034963   
54034            72          5                3           2     1.158311   

       stem-width  stem-color    season  class  
0            1545          11  1.804273      1  
1            1557          11  1.804273      1  
2            1566          11  1.804273      1  
3            1566          11  1.804273      1  
4            1464          11  0.943195      1  
...           ...         ...       ...    ...  
54030         569          12  0.943195      1  
54031         490          12  0.943195      1  
54032         584          12  0.888450      1  
54033         491          12  0.888450      1  
54034         492          12  0.888450      1  

[54035 rows x 9 columns]

In [7]:
df.isnull().sum()

cap-diameter       0
cap-shape          0
gill-attachment    0
gill-color         0
stem-height        0
stem-width         0
stem-color         0
season             0
class              0
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder as LE

In [11]:
le_capdiameter = LE()

In [13]:
df['cap-diameter']= le_capdiameter.fit_transform(df['cap-diameter']) 
df['cap-diameter']

0        1372
1        1461
2        1371
3        1261
4        1305
         ... 
54030      73
54031      82
54032      82
54033      79
54034      72
Name: cap-diameter, Length: 54035, dtype: int64

In [15]:
le_capshape = LE()

In [17]:
df['gill-color']= le_capdiameter.fit_transform(df['gill-color'])
df['gill-color']

0        10
1        10
2        10
3        10
4        10
         ..
54030     2
54031     2
54032     2
54033     2
54034     2
Name: gill-color, Length: 54035, dtype: int64

In [19]:
le_stemheight = LE()

In [21]:
df['stem-height']= le_stemheight.fit_transform(df['stem-height'])
df['stem-height']

0        1447
1        1447
2        1399
3        1442
4        1424
         ... 
54030     446
54031     596
54032     460
54033     520
54034     582
Name: stem-height, Length: 54035, dtype: int64

In [23]:
le_stemwidth = LE()

In [25]:
df['stem-width']= le_stemwidth.fit_transform(df['stem-width'])
df['stem-width']

0        1545
1        1557
2        1566
3        1566
4        1464
         ... 
54030     569
54031     490
54032     584
54033     491
54034     492
Name: stem-width, Length: 54035, dtype: int64

In [27]:
le_stemwidth = LE()

In [29]:
df['stem-color']= le_stemwidth.fit_transform(df['stem-color'])
df['stem-color']

0        11
1        11
2        11
3        11
4        11
         ..
54030    12
54031    12
54032    12
54033    12
54034    12
Name: stem-color, Length: 54035, dtype: int64

In [31]:
X = df.drop(columns=["class"])
y = df["class"]

In [37]:
X

cap-diameter  cap-shape  gill-attachment  gill-color  stem-height  \
0              1372          2                2          10         1447   
1              1461          2                2          10         1447   
2              1371          2                2          10         1399   
3              1261          6                2          10         1442   
4              1305          6                2          10         1424   
...             ...        ...              ...         ...          ...   
54030            73          5                3           2          446   
54031            82          2                3           2          596   
54032            82          5                3           2          460   
54033            79          2                3           2          520   
54034            72          5                3           2          582   

       stem-width  stem-color    season  
0            1545          11  1.804273  
1            1557          11  1.804273  
2            1566          11  1.804273  
3            1566          11  1.804273  
4            1464          11  0.943195  
...           ...         ...       ...  
54030         569          12  0.943195  
54031         490          12  0.943195  
54032         584          12  0.888450  
54033         491          12  0.888450  
54034         492          12  0.888450  

[54035 rows x 8 columns]

In [39]:
y

0        1
1        1
2        1
3        1
4        1
        ..
54030    1
54031    1
54032    1
54033    1
54034    1
Name: class, Length: 54035, dtype: int64

In [43]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [47]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_train)

In [49]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)

In [51]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [55]:
y_pred = knn.predict(X_test_scaled)
y_pred

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)