In [17]:
#shape
import numpy as gy
guru = gy.array([[9,8,7,6],[5,4,3,2]])
guru.shape

(2, 4)

In [41]:
import numpy as np
yougga = np.array([8,7,6,5,4], ndmin=6)
yougga.shape

(1, 1, 1, 1, 1, 5)

In [45]:
yougga

array([[[[[[8, 7, 6, 5, 4]]]]]])

In [79]:
#reshape
import numpy as np
mandhara = np.array([14,13,12,11,10,9,8,7,6,5,4,3,2,1])
cheppundo = mandhara.reshape(2,7)
cheppundo

array([[14, 13, 12, 11, 10,  9,  8],
       [ 7,  6,  5,  4,  3,  2,  1]])

In [99]:
import numpy as np
manikya = np.array([21,22,23,24,25,26,27,28,29,30,31,32])
kallundo = manikya.reshape(3,2,2)
kallundo

array([[[21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28]],

       [[29, 30],
        [31, 32]]])

In [115]:
import numpy as np
kayyil = np.array([[[11,12,13],[14,15,16],[17,18,19]]])
vaarmathiye = kayyil.reshape(-1)
vaarmathiye

array([11, 12, 13, 14, 15, 16, 17, 18, 19])