In [8]:
import numpy as np
water = np.array([7,8,9])
for i in water:
    print (i)

7
8
9


In [20]:
import numpy as np
aqua = np.array([[6,5,4],[3,2,1]])
for e in aqua:
   for c in e:
    print (c)

6
5
4
3
2
1


In [30]:
import numpy as np
aqua = np.array([[[9,8,7],[6,5,4]],[[3,2,1],[11,12,13]]])
for x in aqua:
    for u in x:
        for z in u:
            print (z)

9
8
7
6
5
4
3
2
1
11
12
13


In [34]:
import numpy as np
yours = np.array([[[9,8],[7,6]],[[5,4],[3,2]]])
for r in np.nditer (yours):
    print (r)

9
8
7
6
5
4
3
2


In [9]:
#Joining
import numpy as np
tool1 = np.array ([9,8,7])
tool2 = np.array ([6,5,4])
tool = np.concatenate((tool1,tool2))
print (tool)

[9 8 7 6 5 4]


In [13]:
import numpy as np
box1 = np.array ([[2,4],[1,3]])
box2 = np.array ([[6,8],[5,7]])
box = np.concatenate((box1,box2), axis=1)
print (box)

[[2 4 6 8]
 [1 3 5 7]]


In [21]:
import numpy as np
tooth1 = np.array ([2,4,6])
tooth2 = np.array ([1,3,5])
tooth = np.stack ((tooth1,tooth2), axis=1)
print (tooth)

[[2 1]
 [4 3]
 [6 5]]


In [25]:
import numpy as np
brush1 = np.array ([6,5,4])
brush2 = np.array ([3,2,1])
brush = np.hstack ((brush1,brush2))
print (brush)

[6 5 4 3 2 1]


In [31]:
import numpy as np 
road1 = np.array ([1,3,5])
road2 = np.array ([7,9,11])
road = np.vstack((road1,road2))
print (road)

[[ 1  3  5]
 [ 7  9 11]]


In [35]:
import numpy as np
house1 = np.array ([2,6,24])
house2 = np.array ([4,12,48])
house = np.dstack((house1,house2))
print (house)

[[[ 2  4]
  [ 6 12]
  [24 48]]]
