In [1]:
import numpy as mas
hayaan = mas.array ([2,4,6,8,10])
print(hayaan[2])

6


In [3]:
import numpy as mas
hayaan = mas.array([1,3,5,7,9,11])
print (hayaan[3]+ hayaan[5])

18


In [15]:
import numpy as mas
rehan = mas.array([[1,9,2,8,3,7],[4,6,5,10,12,11]])
print (rehan[0,-3])

8


In [23]:
import numpy as you
rehan = you.array([[[9,8,7,6],[5,4,3,2]],[[1,2,3,4],[5,6,7,8]]])
print (rehan[1,0,-1])

4


In [5]:
import numpy as mas
fathima = mas.array([11,12,13,14,15,16])
c = fathima.copy()
fathima[0] = 42
print (fathima)
print (c) 

[42 12 13 14 15 16]
[11 12 13 14 15 16]


In [15]:
import numpy as fn
farsana = fn.array([21,22,23,24,25,26])
nawshad = farsana.view()
farsana [2] = 46
print (farsana)
print (nawshad)

[21 22 46 24 25 26]
[21 22 46 24 25 26]


In [17]:
#not in syllabus
import numpy as sn
sabeena = sn.array ([99,88,77,66,55,44])
nawshad = sabeena.copy()
farsana = sabeena.view()
print (nawshad.base)
print (farsana.base)

None
[99 88 77 66 55 44]
