In [1]:
import numpy as ak
khan = ak.array([9,8,7,6,5,4,3,2,1])
print(khan[2:7])

[7 6 5 4 3]


In [3]:
import numpy as sk
shahrukhan = sk.array([2,4,6,8,10,12,14,16])
print(shahrukhan[3:])

[ 8 10 12 14 16]


In [7]:
import numpy as sk
shahrukhan = sk.array([2,4,6,8,10,12,14,16])
print (shahrukhan[:6])

[ 2  4  6  8 10 12]


In [16]:
import numpy as sk
salmankhan = sk.array([1,3,5,7,9,11,13,15])
print (salmankhan[-5:])

[ 7  9 11 13 15]


In [18]:
import numpy as ak
aamirkhan = ak.array([1,2,3,4])
print (aamirkhan.dtype)

int32


In [20]:
import numpy as ak
aamirkhan = ak.array(['ferrari','lamborghini','porsche'])
print(aamirkhan.dtype)

<U11


In [17]:
import numpy as ak
aamirkhan = ak.array([4.1,2.1,3.1,6.1])
khan = aamirkhan.astype('i')
print (khan)
print (khan.dtype)

[4 2 3 6]
int32


In [1]:
import numpy as jg
jijigomez = jg.array([1,2,0,4,0,6])
gomez = jijigomez.astype(bool)
print(gomez)
print(gomez.dtype)

[ True  True False  True False  True]
bool
