In [3]:
#dot
import numpy as mas
array1 = mas.array([6,5,4])
array2 = mas.array([3,2,1])
resulting = mas.dot(array1,array2)
print (resulting)

32


In [13]:
#inner
import numpy as mas
array1 = mas.array([[1,3],
                    [5,7]])
array2 = mas.array([[2,4],
                    [6,8]])
resulting = mas.inner(array1,array2)
(resulting)

array([[14, 30],
       [38, 86]])

In [17]:
#outer
import numpy as rr
array1 = rr.array([9,7,5])
array2 = rr.array([8,6,4])
resulting = rr.outer(array1,array2)
resulting

array([[72, 54, 36],
       [56, 42, 28],
       [40, 30, 20]])

In [19]:
#det
import numpy as np
array1 = np.array([[2,4],
                  [6,8]])
resulting = np.linalg.det(array1)
print (resulting)

-8.000000000000002


In [25]:
#solve
import numpy as wu
B = wu.array([[9,7],
              [5,3]])
T = wu.array([3,1])
Z = wu.linalg.solve(B,T)
Z

array([-0.25,  0.75])

In [27]:
#inverse
import numpy as hx
array1 = hx.array([[1,3],
                   {2,4]])
resulting = hx.linalg.inv(array1)
resulting

SyntaxError: closing parenthesis ']' does not match opening parenthesis '{' (4272945124.py, line 4)