In [9]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
import numpy 
arr = numpy.array([1,2,3,4,5,6])
print (arr)

[1 2 3 4 5 6]


In [15]:
import numpy 
print (numpy.__version__)

1.26.4


In [17]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print (arr)
print (type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [19]:
import numpy as npy
ashish = npy.array(64)
print (ashish)


64


In [31]:
import numpy as nmy
arif = nmy.array([[1,2,3],[4,5,6]])
print (arif)

[[1 2 3]
 [4 5 6]]


In [33]:
import numpy as mas
anila = mas.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (anila)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
import numpy as ss
a = ss.array(32)
n = ss.array([1,2,3,4,5])
j = ss.array([[1,2,3],[4,5,6]])
l = ss.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print (a.ndim)
print (n.ndim)
print (j.ndim)
print (l.ndim)

0
1
2
3


In [52]:
import numpy as rrr
rehan = rrr.array ([1,2,3,4,5], ndmin = 4)
print (rehan)
print ('no of dimensions :', rehan.ndim)

[[[[1 2 3 4 5]]]]
no of dimensions : 4
