In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import ensemble
from sklearn import tree
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [4]:
data = {
    'Age' :[22, 25, 30, 35, 40, 50],
    'Income' :['low','medium','high','low','high','medium'],
    'Buys_Product':['no','yes','yes','no','yes','no']
}

In [5]:
df = pd.DataFrame(data)

In [6]:
label_encoder_age = LabelEncoder()
label_encoder_income = LabelEncoder()
label_encoder_target = LabelEncoder()

In [11]:
df['Age'] = label_encoder_age.fit_transform(df['Age'])
df['Income'] = label_encoder_income.fit_transform(df['Income'])
df['Buys_Product'] = label_encoder_target.fit_transform(df['Buys_Product'])

In [26]:
X = df[['Age','Income']].values
y = df['Buys_Product'].values

In [30]:
X

array([[0, 1],
       [1, 2],
       [2, 0],
       [3, 1],
       [4, 0],
       [5, 2]], dtype=int64)

In [34]:
y

array([0, 1, 1, 0, 1, 0], dtype=int64)

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
X_train

array([[5, 2],
       [2, 0],
       [4, 0],
       [3, 1]], dtype=int64)

In [46]:
X_test

array([[0, 1],
       [1, 2]], dtype=int64)

In [50]:
y_train

array([0, 1, 1, 0], dtype=int64)

In [54]:
y_test

array([0, 1], dtype=int64)

In [58]:
classifier=RandomForestClassifier(n_estimators=10, criterion='entropy')
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [62]:
y_pred=classifier.predict(X_test)

In [66]:
y_pred

array([0, 0], dtype=int64)

In [74]:
new_sample = [[4,2]]
predicted = classifier.predict(new_sample)
print('Predicted class:', label_encoder_target.inverse_transform(predicted))

Predicted class: [0]


In [78]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import ensemble
from sklearn import tree
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [82]:
df = pd.read_csv('Heart Attack Data Set.csv')

In [86]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [90]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [94]:
x = df.drop('target', axis=1).values
y = df['target'].values

In [98]:
x

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [100]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [102]:
x_train , x_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state=42)

In [104]:
x_train

array([[42.,  1.,  1., ...,  2.,  0.,  2.],
       [58.,  1.,  0., ...,  2.,  0.,  3.],
       [46.,  1.,  2., ...,  1.,  0.,  2.],
       ...,
       [69.,  1.,  3., ...,  1.,  1.,  2.],
       [46.,  1.,  0., ...,  2.,  0.,  3.],
       [63.,  0.,  1., ...,  2.,  2.,  2.]])

In [106]:
x_test

array([[5.70e+01, 1.00e+00, 0.00e+00, 1.50e+02, 2.76e+02, 0.00e+00,
        0.00e+00, 1.12e+02, 1.00e+00, 6.00e-01, 1.00e+00, 1.00e+00,
        1.00e+00],
       [5.90e+01, 1.00e+00, 3.00e+00, 1.70e+02, 2.88e+02, 0.00e+00,
        0.00e+00, 1.59e+02, 0.00e+00, 2.00e-01, 1.00e+00, 0.00e+00,
        3.00e+00],
       [5.70e+01, 1.00e+00, 2.00e+00, 1.50e+02, 1.26e+02, 1.00e+00,
        1.00e+00, 1.73e+02, 0.00e+00, 2.00e-01, 2.00e+00, 1.00e+00,
        3.00e+00],
       [5.60e+01, 0.00e+00, 0.00e+00, 1.34e+02, 4.09e+02, 0.00e+00,
        0.00e+00, 1.50e+02, 1.00e+00, 1.90e+00, 1.00e+00, 2.00e+00,
        3.00e+00],
       [7.10e+01, 0.00e+00, 2.00e+00, 1.10e+02, 2.65e+02, 1.00e+00,
        0.00e+00, 1.30e+02, 0.00e+00, 0.00e+00, 2.00e+00, 1.00e+00,
        2.00e+00],
       [5.70e+01, 1.00e+00, 2.00e+00, 1.50e+02, 1.68e+02, 0.00e+00,
        1.00e+00, 1.74e+02, 0.00e+00, 1.60e+00, 2.00e+00, 0.00e+00,
        2.00e+00],
       [4.60e+01, 0.00e+00, 0.00e+00, 1.38e+02, 2.43e+02, 0.00e+00,
  

In [108]:
y_train

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
      dtype=int64)

In [112]:
y_train

array([1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
      dtype=int64)

In [118]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [122]:
classifier= RandomForestClassifier(n_estimators=10,criterion="entropy")
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [126]:
y_pred=classifier.predict(x_test)
y_pred

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [138]:
new_sample = [[8,4,3,6,2,5,1,4,8,7,9,3,6]]
predicted = classifier.predict(new_sample)
print('Predicted class:',label_encoder_target.inverse_transform(predicted))

Predicted class: [0]


In [7]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn import tree
from sklearn import ensemble 
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [9]:
df = pd.read_csv('airlines_delay.csv')
df

Flight    Time  Length Airline AirportFrom AirportTo  DayOfWeek  Class
0       2313.0  1296.0   141.0      DL         ATL       HOU          1      0
1       6948.0   360.0   146.0      OO         COS       ORD          4      0
2       1247.0  1170.0   143.0      B6         BOS       CLT          3      0
3         31.0  1410.0   344.0      US         OGG       PHX          6      0
4        563.0   692.0    98.0      FL         BMI       ATL          4      0
...        ...     ...     ...     ...         ...       ...        ...    ...
539377  6973.0   530.0    72.0      OO         GEG       SEA          5      1
539378  1264.0   560.0   115.0      WN         LAS       DEN          4      1
539379  5209.0   827.0    74.0      EV         CAE       ATL          2      1
539380   607.0   715.0    65.0      WN         BWI       BUF          4      1
539381  6377.0   770.0    55.0      OO         CPR       DEN          2      1

[539382 rows x 8 columns]

In [11]:
df.isnull().sum()

Flight         0
Time           0
Length         0
Airline        0
AirportFrom    0
AirportTo      0
DayOfWeek      0
Class          0
dtype: int64

In [15]:
X = df.drop('Class',axis=1).values
y = df['Class'].values

In [17]:
X

array([[2313.0, 1296.0, 141.0, ..., 'ATL', 'HOU', 1],
       [6948.0, 360.0, 146.0, ..., 'COS', 'ORD', 4],
       [1247.0, 1170.0, 143.0, ..., 'BOS', 'CLT', 3],
       ...,
       [5209.0, 827.0, 74.0, ..., 'CAE', 'ATL', 2],
       [607.0, 715.0, 65.0, ..., 'BWI', 'BUF', 4],
       [6377.0, 770.0, 55.0, ..., 'CPR', 'DEN', 2]], dtype=object)

In [19]:
y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [23]:
X_train

array([[263.0, 865.0, 350.0, ..., 'IAD', 'LAX', 2],
       [2661.0, 750.0, 85.0, ..., 'MHT', 'EWR', 3],
       [1427.0, 830.0, 80.0, ..., 'MDW', 'BNA', 2],
       ...,
       [1153.0, 1055.0, 185.0, ..., 'DTW', 'FLL', 2],
       [1006.0, 1180.0, 70.0, ..., 'MDW', 'DTW', 5],
       [1275.0, 560.0, 328.0, ..., 'JFK', 'SLC', 6]], dtype=object)

In [43]:
X_test

array([[728.0, 610.0, 375.0, ..., 'PVD', 'LAS', 7],
       [716.0, 685.0, 243.0, ..., 'SJU', 'JFK', 2],
       [1103.0, 590.0, 65.0, ..., 'ORD', 'STL', 5],
       ...,
       [1488.0, 1150.0, 171.0, ..., 'IAH', 'DTW', 3],
       [714.0, 540.0, 60.0, ..., 'STL', 'SDF', 3],
       [751.0, 1210.0, 116.0, ..., 'BWI', 'HSV', 4]], dtype=object)

In [47]:
y_train

array([1, 0, 1, ..., 1, 0, 0], dtype=int64)

In [49]:
y_test

array([0, 1, 0, ..., 1, 1, 1], dtype=int64)

In [51]:
classifier=RandomForestClassifier(n_estimators=10, criterion='entropy')
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: 'AA'